# Checks whether the pushed commit can be build with PIO. Only triggered on normal push to the mega branch without tag and with pull requests targeting mega

name: Build

on:
  push:
    branches: [mega]
    tags-ignore: '**'
    paths-ignore:
      - 'dist/Release_notes.txt'
  pull_request:
    branches: [mega]

permissions:
  contents: read

jobs:
  documentation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/requirements.txt') }}
      - name: Build documentation
        run: |
          cd docs
          sudo apt install imagemagick zip
          pip install -r requirements.txt
          make html
          cd ..
          zip -r -qq ESPEasy_docs.zip docs/build/*
      - uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: ESPEasy_docs.zip
  generate-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: set-matrix
        run: |
          pip install platformio
          python tools/ci/generate-matrix.py

  build:
    needs: generate-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      - uses: actions/cache@v3
        if: ${{ contains(matrix.env, 'esp32') }}
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-esp32-${{ hashFiles('platformio*.ini') }}
      - uses: actions/cache@v3
        if: ${{ contains(matrix.env, 'esp8266') }}
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-esp8266-${{ hashFiles('platformio*.ini') }}
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt install binutils build-essential libffi-dev libgit2-dev
          pip3 install --upgrade pip
          pip install -r requirements.txt
          platformio update
      - name: Build and archive
        id: build-and-archive
        env:
          CHIP: ${{ matrix.chip }}
          ENV: ${{ matrix.env }}
        run: |
          python tools/ci/build-and-archive.py
      - uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            bin
          if-no-files-found: ignore

  # Testing here instead of running a release
  prepare-dist:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/requirements.txt') }}
      - name: Package utilities
        run: |
          cd dist
          zip -r -qq ../ESPEasy_dist.zip *
          cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: Distribution
          path: |
            ESPEasy_dist.zip

  pre-release:
    needs: [build, prepare-dist]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - run: |
          ls -R
          sudo apt install zipmerge zip
          cd artifacts/Binaries
          mkdir bin
          mv * bin
          find . -name '*ESP82*' |zip -@ ../../ESPEasy_ESP82xx.zip
          find . -name '*ESP32*' |zip -@ ../../ESPEasy_ESP32.zip 
          cd ../..
          mv artifacts/Distribution/ESPEasy_dist* .
          cp ESPEasy_dist.zip ESPEasy_ESP82xx_binaries.zip
          mv ESPEasy_dist.zip ESPEasy_ESP32_binaries.zip
          zipmerge ESPEasy_ESP82xx_binaries.zip ESPEasy_ESP82xx.zip
          zipmerge ESPEasy_ESP32_binaries.zip ESPEasy_ESP32.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Pre-release-${{ github.event.repository.updated_at }}
          path: |
            ESPEasy_ESP82xx_binaries.zip
            ESPEasy_ESP32_binaries.zip
          if-no-files-found: ignore
